name: .NET Build, Test and Publish

# Trigger workflow on push or pull request to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test SPMminorproject
    runs-on: windows-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0   # Fetch full history to avoid Git errors

    # Step 2: Setup .NET
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'   # Change if your project uses another version

    # Step 3: Restore dependencies
    - name: Restore NuGet packages
      run: dotnet restore

    # Step 4: Build project
    - name: Build project
      run: dotnet build --configuration Release --no-restore

    # Step 5: Run tests
    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    # Step 6: Publish (optional - creates deployable files)
    - name: Publish project
      run: dotnet publish -c Release -o publish
